theme: jekyll-theme-cayman
title: Alex Irlbeck & Cameron Roehlk
description: CattleTEC market forecasting and analysis project. The goal of this project is to bring in commodity values that matter to cow / calf in order to improve management decisions when it comes to marketing their livestock.

